#define GLUE(g1,g2) g1##g2
#define LIST_OF_BONES(prefix) \
	SECTION_A(GLUE(prefix,_mpdObj01_A)) \
	SECTION_A(GLUE(prefix,_mpdObj02_A)) \
	SECTION_A(GLUE(prefix,_mpdObj03_A)) \
	SECTION_A(GLUE(prefix,_mpdObj04_A)) \
	SECTION_A(GLUE(prefix,_mpdObj05_A)) \
	SECTION_ASE(GLUE(prefix,_mpdObj01_ASE)) \
	SECTION_ASE(GLUE(prefix,_mpdObj02_ASE)) \
	SECTION_ASE(GLUE(prefix,_mpdObj03_ASE)) \
	SECTION_ASE(GLUE(prefix,_mpdObj04_ASE)) \
	SECTION_ASE(GLUE(prefix,_mpdObj05_ASE)) \
	SECTION_ASE(GLUE(prefix,_mpdObj06_ASE)) \
	SECTION_ASE(GLUE(prefix,_mpdObj07_ASE)) \
	SECTION_B(GLUE(prefix,_mpdObj01_B)) \
	SECTION_B(GLUE(prefix,_mpdObj02_B)) \
	SECTION_B(GLUE(prefix,_mpdObj03_B)) \
	SECTION_B(GLUE(prefix,_mpdObj04_B)) \
	SECTION_B(GLUE(prefix,_mpdObj05_B)) \
	SECTION_C(GLUE(prefix,_mpdObj01_C)) \
	SECTION_C(GLUE(prefix,_mpdObj02_C)) \
	SECTION_C(GLUE(prefix,_mpdObj03_C)) \
	SECTION_C(GLUE(prefix,_mpdObj04_C)) \
	SECTION_C(GLUE(prefix,_mpdObj05_C)) \
	SECTION_D(GLUE(prefix,_mpdObj01_D)) \
	SECTION_D(GLUE(prefix,_mpdObj02_D)) \
	SECTION_D(GLUE(prefix,_mpdObj03_D)) \
	SECTION_D(GLUE(prefix,_mpdObj04_D)) \
	SECTION_D(GLUE(prefix,_mpdObj05_D)) \
	SECTION_E(GLUE(prefix,_mpdObj01_E)) \
	SECTION_E(GLUE(prefix,_mpdObj02_E)) \
	SECTION_E(GLUE(prefix,_mpdObj03_E)) \
	SECTION_E(GLUE(prefix,_mpdObj04_E)) \
	SECTION_E(GLUE(prefix,_mpdObj05_E)) \
	SECTION_FCR(GLUE(prefix,_mpdObj01_FCR)) \
	SECTION_FCR(GLUE(prefix,_mpdObj02_FCR)) \
	SECTION_FCR(GLUE(prefix,_mpdObj03_FCR)) \
	SECTION_FCR(GLUE(prefix,_mpdObj04_FCR)) \
	SECTION_FCR(GLUE(prefix,_mpdObj05_FCR)) \
	SECTION_FCR(GLUE(prefix,_mpdObj06_FCR)) \
	SECTION_FCR(GLUE(prefix,_mpdObj07_FCR)) \
	SECTION_FCR(GLUE(prefix,_mpdObj08_FCR)) \
	SECTION_FCR(GLUE(prefix,_mpdObj09_FCR)) \
	SECTION_FCR(GLUE(prefix,_mpdObj10_FCR)) \
	SECTION_FCR(GLUE(prefix,_mpdObj11_FCR)) \
	SECTION_FCR(GLUE(prefix,_mpdObj12_FCR)) \
	SECTION_FCR(GLUE(prefix,_mpdObj13_FCR)) \
	SECTION_FCR(GLUE(prefix,_mpdObj14_FCR)) \
	SECTION_FCR(GLUE(prefix,_mpdObj15_FCR)) \
	SECTION_FCR(GLUE(prefix,_mpdObj16_FCR)) \
	SECTION_PPOS(GLUE(prefix,_mpdObj01_PPos)) \
	SECTION_PPOS(GLUE(prefix,_mpdObj02_PPos)) \
	SECTION_PPOS(GLUE(prefix,_mpdObj03_PPos))